# Generated by Django 4.1 on 2022-11-02 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nobokek', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='alamat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='masalah',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='nama',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contactus',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
