# Generated by Django 4.1 on 2022-11-02 04:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('add', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_pesan_reportuser_delete_barangwishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportuser',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reportuser',
            name='userAdd',
        ),
        migrations.AddField(
            model_name='reportuser',
            name='userAdd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='add.money'),
        ),
    ]
