# Generated by Django 4.1 on 2022-11-02 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_reportuser_user_remove_reportuser_useradd_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportUser',
        ),
    ]
