# Generated by Django 4.1 on 2022-11-02 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0004_delete_reportuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pesan',
        ),
    ]
